name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
    - uses: actions/checkout@v4
    - name: Install NodeJS >= 18
    - uses: actions/setup-node@v4
      with:
        node-version: 18
    - name: Install dependencies    
    - run: npm ci
    - run: npm test
    

    #- name: configure
    #  run: ./configure

    #- name: Install dependencies
    #  run: make

    #- name: Run check
    #  run: make check

    #- name: Run distcheck
    #  run: make distcheck
