name: Makefile CI
on: [push]  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Install NodeJS >= 18
      uses: actions/setup-node@v4
      with:
        node-version: 18
        
      # Ставим зависимости Install dependencies
    - run: npm install
      # Запускаем линтер
    - run: npm run lint
      # Запускаем тесты
      # у шагов может быть имя, иногда это помогает отладке
      # имя выводится на Github при просмотре сборки
    - name: run tests
       run: npm test # name и run относятся к одной задаче, поэтому дефис ставится только перед name
      
      
      
    
   
