name: Makefile CI
on: [push]  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Install NodeJS >= 18
      uses: actions/setup-node@v4
      with:
        node-version: 18
        
      # Ставим зависимости Install dependencies
    - run: npm install
      # Запуск линтера
    - run: npm run lint
      # Запуск тестов
    - name: run tests
      run: npm test 
      # name и run относятся к одной задаче, поэтому дефис только перед name
      
      
      
    
   
